# Generated by Django 2.1.7 on 2019-03-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_models', '0003_auto_20190310_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30, verbose_name='Cars name')),
                ('year', models.CharField(max_length=4, verbose_name='Cars year')),
                ('mileage', models.CharField(max_length=10, verbose_name='Cars mileage')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
