# Generated by Django 2.1.7 on 2019-03-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_models', '0005_auto_20190310_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=100, verbose_name='Url'),
        ),
    ]
