# Generated by Django 2.1.7 on 2019-03-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_models', '0006_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=100, verbose_name='Url'),
        ),
    ]
