# Generated by Django 2.1.7 on 2019-03-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_models', '0007_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Url'),
        ),
    ]
