# Generated by Django 2.1.7 on 2019-04-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Пользователь')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('text', models.TextField(max_length=200, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'КонтактФорма',
                'verbose_name_plural': 'КонтактФормы',
            },
        ),
    ]
