# Generated by Django 2.1.7 on 2019-04-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_auto_20190407_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
