# Generated by Django 2.1.7 on 2019-04-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_contactformmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
