# Generated by Django 2.1.7 on 2019-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0005_auto_20190411_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='username',
            field=models.CharField(max_length=20, null=True, verbose_name='Пользователь'),
        ),
    ]
