# Generated by Django 2.1.7 on 2019-04-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0006_auto_20190411_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='username',
            field=models.CharField(blank=True, max_length=20, verbose_name='Пользователь'),
        ),
    ]
